feat: Add release candidate validation
GoogleCloudPlatform/functions-framework-go pull request #124
Opened 2022-04-12 20:34 UTC by anniefu

Runs buildpack integration tests before the release-please GitHub Action
creates a release candidate PR.

2022-04-12 22:33 UTC, grant requested changes
Can you add a detailed PR description?

What is this really testing and what type of failures can we now uniquely detect with this action?

Is there an overall design for this validation work? There seems to be a lot of hardcoded values here.

2022-04-12 22:52 UTC, anniefu commented
> Can you add a detailed PR description?
> 
> What is this really testing and what type of failures can we now uniquely detect with this action?
> 
> Is there an overall design for this validation work? There seems to be a lot of hardcoded values here.

Added the link to the functions framework conformance PR that describes the integration test.

The only hardcoded value that is unfortunate is the builder tag, which can hopefully be removed if GCF tags their builders with latest. Otherwise, the values you see input are the same as required for `conformance.yml` or any conformance test run.

2022-04-18 17:32 UTC, grant approved these changes
LGTM. I'm not sure how this will orchestrate in practice, but we can try it out.

2022-04-18 17:32 UTC, grant commented on .github/workflows/release-please.yml
> +      builder-tag: 'go113_20220320_1_13_15_RC00'
Perhaps add a note here as to why we're using this builder / how we will update this in the future.

2022-04-19 23:45 UTC, merged