feat: Allow registering multiple functions with one server for local testing
GoogleCloudPlatform/functions-framework-go pull request #154
Opened 2022-08-12 23:47 UTC by jihuin

There are two ways to test multiple functions within one server. 

1. Declaratively register multiple functions (e.g. calling `functions.HTTP()`) and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, all registered functions will be served  at "/{func_name}".
2. Manually register the handers (e.g. calling `funcframework.RegisterHTTPFunctionContext()`)  and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case,  the registered handlers will be served at the user defined path.

Closes #109

2022-08-16 18:00 UTC, anniefu requested changes

2022-08-17 01:16 UTC, jihuin commented on funcframework/framework.go
> +		} else if lastFnWithoutName := registry.Default().GetLastFunctionWithoutName(); lastFnWithoutName != nil {
Done

2022-08-17 01:16 UTC, jihuin commented on internal/registry/registry.go
> +// GetLastFunctionWithoutName returns the last function that's not registered declaratively.
Done.

2022-08-17 01:16 UTC, jihuin commented on internal/registry/registry_test.go
> +	testCases := []struct {
Done.

2022-08-17 01:17 UTC, jihuin commented on internal/registry/registry.go
> +	function.Path = "/" + function.Name
Done

2022-08-17 01:18 UTC, jihuin commented on internal/registry/registry.go
> +	r.functions[function.Name] = &function
I prefer not allowing the case that both are empty

2022-08-17 01:18 UTC, jihuin commented on internal/registry/registry.go
> +	function := RegisteredFunction{
Done

2022-08-17 01:18 UTC, jihuin commented on internal/registry/registry.go
> +func (r *Registry) DeleteRegisteredFunction(name string) {
Deleted

2022-08-17 16:39 UTC, anniefu commented on internal/registry/registry.go
> +	function := RegisteredFunction{
Nice.

2022-08-17 16:39 UTC, anniefu approved these changes

2022-08-17 20:18 UTC, merged