feat: configure codeql vulnerability scanning
GoogleCloudPlatform/functions-framework-go pull request #170
Opened 2023-01-25 21:17 UTC by kenneth-rosario

2023-01-27 01:24 UTC, HKWinterhalter commented on funcframework/events.go
> +			fmt.Println(escapedLog)
also, what's the reason for removing newlines?

2023-01-27 01:24 UTC, HKWinterhalter commented on funcframework/framework.go
> +	return newMessage
same comment as above, consolidate this to one or two lines

2023-02-01 21:50 UTC, HKWinterhalter approved these changes

2023-02-01 21:50 UTC, kenneth-rosario commented on funcframework/events.go
> +			fmt.Println(escapedLog)
Synced offline

2023-02-02 20:57 UTC, anniefu requested changes

2023-02-02 20:57 UTC, anniefu commented on .github/workflows/codeql.yml
> +  schedule:
[nit] do you need to include this section if it's not running?

2023-02-02 20:57 UTC, anniefu commented on .github/workflows/codeql.yml
> +        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
[nit] can probably remove these comments except maybe the last line that links to docs. probably same below

2023-02-02 20:57 UTC, anniefu commented on .github/workflows/codeql.yml
> +        languages: ${{ matrix.language }}
[nit] Given the repo we're in, we can probably just fill this in with Go and not use a matrix

2023-02-02 20:57 UTC, anniefu commented on funcframework/events.go
> +			replacer := strings.NewReplacer("\n", "", "\r", "")
Based on the alert's stack trace, we should probably do this on line 53 of pubsub.go and apply it just to the path.

We probably don't want to remove whitespaces everywhere in the error message as something in our own code might have added it to make the error message more readable.

2023-02-02 20:57 UTC, anniefu commented on funcframework/framework.go
> +	escapedMsg := sanitizeMessage(msg)
We actually need to keep the old behavior here of *adding* a newline to the end of the message. Cloud Logging uses newlines to detect when a new log starts. So if a user didn't add a newline to the end of their function's log like this:

```
log.Print("this doesn't end with a new line")
```

And you invoke the function twice in a row, their Cloud Logging might show something like

`this doesn't end with a new linethis doesn't end with a new line`

When you really want a separate line for each invocation. (Or something similar to that, I dont' remember the exact scenario).

2023-02-03 18:45 UTC, anniefu commented on internal/events/pubsub/pubsub.go
> +		replacer := strings.NewReplacer("\n", "", "\r", "")
[nit] add comment for why we're doing this

2023-02-03 18:45 UTC, anniefu commented on funcframework/framework.go
> +	fmt.Fprint(w, html.EscapeString(msg))
Was the code scanning complaining about this one? If not, we probably want to leave it alone as there may be customers expecting their strings to be formatted a certain way and we're just changing it underneath them.

2023-02-08 20:35 UTC, anniefu approved these changes
Similar to PHP one, use `chore:` instead of `feat:` so we don't impact the version number of the next release

2023-02-09 22:23 UTC, merged