Explicitly use localhost as host when starting server to stop warning
GoogleCloudPlatform/functions-framework-go pull request #63
Opened 2020-12-17 20:05 UTC by grant

Fixes https://github.com/GoogleCloudPlatform/functions-framework-go/issues/62, an OSX warning starting a server.

Would like a review from someone more knowledgeable in Go.

---

See related articles like:

https://medium.com/@leeprovoost/suppressing-accept-incoming-network-connections-warnings-on-osx-7665b33927ca

2021-01-07 18:16 UTC, grayside requested changes
Binding to `localhost` is not appropriate for inside a container. It expects requests to originate from inside the container. Typical practice is not to specify the host or to specify `0.0.0.0` as a stand-in for a wildcard.

This is something we mostly live with, fixing it could be done with a flag or perhaps detecting if running in a Darwin-based environment on the assumption we won't be running macOS inside the container.

2021-01-12 19:00 UTC, grant commented
> Binding to `localhost` is not appropriate for inside a container. It expects requests to originate from inside the container. Typical practice is not to specify the host or to specify `0.0.0.0` as a stand-in for a wildcard.
> 
> This is something we mostly live with, fixing it could be done with a flag or perhaps detecting if running in a Darwin-based environment on the assumption we won't be running macOS inside the container.

Thanks.

This issue is not a priority for me, so I can't look at alternatives. Closing this PR.

2021-01-12 19:00 UTC, closed without merging

2021-01-19 15:15 UTC, picaoao commented
I think an optional env would be fine.
What do you think ?

2021-01-19 16:45 UTC, grant commented
> I think an optional env would be fine.
> What do you think ?

Yes perhaps. Let's talk more in the GitHub issue.